apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-order
  namespace: eatfresh
  labels:
    app: weborder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weborder
  template:
    metadata:
      labels:
        app: weborder
    spec:
      containers:
      - name: weborder
        image: registry.gitlab.au.dk/wao-exercises1/eatfresh/eatfresh.orderprocessing:0.0.03.v
        ports:
        - containerPort: 5126
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ACCEPT_EULA
          valueFrom:
            secretKeyRef:
              name: sql-secret-order
              key: ACCEPT_EULA
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret-order
              key: MSSQL_SA_PASSWORD
        - name: RABBITMQ_HOST
          value: rabbitmq.eatfresh.svc.cluster.local
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASS
          value: guest
        resources:
          requests:
            cpu: "150m"
            memory: "64Mi"
          limits:
            cpu: "600m"
            memory: "128Mi"
        volumeMounts:
        - name: config-volume-order
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume-order
        configMap:
          name: server-config-order
      imagePullSecrets:
      - name: my-registry-credentials
