apiVersion: v1
kind: Service
metadata:
  name: server-service-order
  namespace: eatfresh
spec:
  selector:
    app: weborder
  ports:
    - name: port1
      protocol: TCP
      port: 80
      targetPort: 5126
  type: ClusterIP