apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config-order
  namespace: eatfresh
data:
  appsettings.json: |-
    {
      "ConnectionStrings": {
        "DefaultConnection": "Server=db-OrderApp2,1433;Database=Orderbd62;User=sa;Password=Orderwao;TrustServerCertificate=True"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }

  rel_url_path: "/grp-13/order"
