apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-volume-pv-order
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: sql-pvc-order
    namespace: eatfresh
  hostPath:
    path: "~/slet/"