apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ordersql-pvc
  namespace: app
spec:
  storageClassName: eatfreshstorageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi