apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-volume-pv
spec:
  storageClassName: "nfs-client"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: sql-pvc-order
    namespace: eatfresh
  hostPath:
    path: "~/slet/"