apiVersion: v1
kind: PersistentVolume
metadata:
  name:  orderdb-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: orderdb-pvc
    namespace: eatfresh
  hostPath:
    path: "~/slet/"
